### ISSUE TITLE
magit-blame C-e not like C-y

### ISSUE THREAD

**Issue by Eluminae** [emacs-evil/evil-magit#30]
Hello everyone,
I just found a little problem with magit-blame mode.

When you press C-y you effectively scrollup.
But, when you C-e, you scrolldown but you are blocked by the git user on top of the screen.

Maybe I have to configurate something ?
Ty very much. I expect I'd be clear.

**Comment by justbur** [comment]
For me, `C-y` and `C-e` are bound to the right functions in blame mode. This means it's not a evil-magit issue because evil-magit is only intended to get the bindings right. 

Some quick debugging on my side suggests that there is an issue with magit. `M-: (scroll-up 1)` has no effect sometimes, which is the built-in function `evil-scroll-line-down` depends on.

**Comment by justbur** [comment]
In other words, please report this to magit.
