### ISSUE TITLE
Can we bind escape to quit the transient/popup windows

### ISSUE THREAD

**Issue by ChoppinBlockParty** [emacs-evil/evil-magit#77]
```
       ;; NOTE This is now transient-map and the binding is C-g.
       ;; ((emacs) magit-popup-mode-map "<escape>" "q")
```
I see that with the new rework of popus (for what ever reason they decided to change it), escape is not working anymore, Is there a way to bring it back to work?

**Comment by justbur** [comment]
The simplest thing to do is
```elisp
(define-key transient-map (kbd "<escape>") 'transient-quit-one)
```
but that affects all transient maps, so I don't want to add that to evil-magit. Of course, it's fine for you to add that to your configuration. 

There doesn't seem to be an easy way of doing this for just the transient maps in magit, but I might look into this later

**Comment by rbugajewski** [comment]
> but that affects all transient maps, so I don't want to add that to evil-magit.

So the right thing to do would be to add `evil-collection-transient` to `evil-collection` and just rebind C-g to escape (for a first, fast version)?

I don’t understand the reasoning here, because it is quite obvious that Evil users don’t want to deal with C-g at all.

Or what would speak against an alternative solution where rebinding transient would happen only temporarily while magit buffers are active? Couldn’t this be done as part of `evil-magit`?
